### ISSUE TITLE
Support Ruby 2.5.x

### ISSUE THREAD

**Issue by tcdowney** [cloudfoundry/bosh-package-ruby-release#11]
Ruby 2.3 has been EOL-ed and is no longer receiving any security updates. This will happen for Ruby 2.4.x in March 2020. Can we get this release updated so that downstream teams can begin consuming it well before then?

See:
https://www.ruby-lang.org/en/news/2019/03/31/support-of-ruby-2-3-has-ended

Thanks! 🦃
Tim && @cwlbraa

**Comment by mrosecrance** [comment]
Tracking story: https://www.pivotaltracker.com/story/show/165360406

**Comment by charleshansen** [comment]
done, let us know if it works
