### ISSUE TITLE
`ruby-2.4.6-r0.4.0` cannot be vendored

### ISSUE THREAD

**Issue by pianohacker** [cloudfoundry/bosh-package-ruby-release#12]
Attempting to use the package from the `v0.4.0` tag results in the following error:

```console
$ bosh vendor-package ruby-2.4.6-r0.4.0 .../releases/ruby-release
Expected to find package 'ruby-2.4.6-r0.4.0'

Exit code 1
```

It looks like there might not have been a final release with that package? (This guess is based on the lack of relevant files in `.final_builds`.

**Comment by drnic** [comment]
I just checked latest and is working:

```
$ bosh vendor-package ruby-2.6.4-r0.18.0 ../ruby-release
-- Started downloading 'ruby-2.6.4-r0.18.0/4f54812986f52f33dcd9ef18e91e40358fe95ccd1db9abd1c2ecb09d6f21e18f' (sha1=sha256:8e708b1d03aa85768450287556a1615a6f4bdd31f53866130e7c3f4b3704fbcf)
...
```

**Comment by aashah** [comment]
Hmm, please re-open if this is still an issue. Looks like there's some age to the issue, and it might potentially be resolved.
