### ISSUE TITLE
Packaging fails when compiling on bosh create-env in rootless container

### ISSUE THREAD

**Issue by videlov** [cloudfoundry/bosh-package-ruby-release#18]
We run currently into a problem while deploying BOSH on AWS. Issue is on compile phase during packaging of the ruby-release as part of `bosh create-env`, we get:

```
...
+ tar zxvf rubygems-3.1.2.tgz
tar: rubygems-3.1.2/CODE_OF_CONDUCT.md: Cannot change ownership to uid 218038053, gid 2033490572: Invalid argument
tar: rubygems-3.1.2/hide_lib_for_update/note.txt: Cannot change ownership to uid 218038053, gid 2033490572: Invalid argument
```

We did create an issue in rubygems project, but they are not in a hurry to fix it: https://github.com/rubygems/rubygems/issues/3977

Could you solve this by adding a `--no-same-owner` parameter to the `tar zxvf` command in here:
https://github.com/bosh-packages/ruby-release/blob/1b7fbfb8567391e20596f4754eb8faaf65fb0a43/packages/ruby-2.5.8-r0.32.0/packaging#L52

and also for all ruby versions? Solution could be:
https://github.com/bosh-packages/ruby-release/pull/19

as far as I remember this was automatically bumped from a CI pipeline, but we don't have access to it.

Thanks,
@videlov

**Comment by mrosecrance** [comment]
Solved https://github.com/bosh-packages/ruby-release/pull/20
