### ISSUE TITLE
Invalid `compile.env` and `runtime.env` if `envsubst` is not present durring packaging step

### ISSUE THREAD

**Issue by aramprice** [cloudfoundry/bosh-package-ruby-release#31]
If the ruby-package is "packaged" in a context where the `envsubst` command is not present the resulting package will not be functional.

> This use of `envsubst` here is causing issues when the ruby package is "packaged" in an environment where `envsubst` does not exist. In particular when running `bosh create-env`, the execution context can be highly variable.
> 
> The consequence is that when `envsubst` is  not present the two files `${BOSH_INSTALL_TARGET}/bosh/compile.env` and `${BOSH_INSTALL_TARGET}/bosh/runtime.env` are empty. This results in a failure when running `bosh create-env` with an error about not being able to find the `ruby` and/or `bundle` command(s).
> 
> See https://github.com/bosh-packages/ruby-release/pull/30/files#r1037669009

**Comment by jpalermo** [comment]
Fixed via https://github.com/bosh-packages/ruby-release/commit/f390302c17b090bb7d449e0fef6798986b812c00
