### ISSUE TITLE
Tag for version 0.0.5 does not exists

### ISSUE THREAD

**Issue by frodenas** [cloudfoundry/bosh-package-ruby-release#4]
Can you please create a github release/tag for version 0.0.5?

**Comment by dpb587-pivotal** [comment]
Tagged [v0.0.5](https://github.com/bosh-packages/ruby-release/releases/tag/v0.0.5)

**Comment by frodenas** [comment]
Thanks @dpb587-pivotal!

**Comment by cppforlife** [comment]
@frodenas why did you need a tag for this repo out of curiosity? are you not consuming final releases?

**Comment by frodenas** [comment]
I am consuming final releases, but I have a CI pipeline that bumps the ruby vendored package on my releases when it detects there's a new version (release/tag) of this release.
