### ISSUE TITLE
Upgrade to rubygems 2.7.6

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/bosh-package-ruby-release#6]
We currently bundle 2.7.3 from Nov 2017.

From https://rubygems.org/gems/rubygems-update

VERSIONS:
2.7.6 - February 16, 2018 (806 KB)
2.7.5 - February 06, 2018 (804 KB)
2.7.4 - December 25, 2017 (803 KB)
2.7.4.pre1 - December 25, 2017 (803 KB)
2.7.3 - November 28, 2017 (803 KB)

**Comment by cppforlife** [comment]
ruby-2.4-r4 package includes this.
